### ISSUE TITLE
Anisotropic vs. Semi-isotropic pressure scaling

### ISSUE THREAD

**Issue by slochower** [callumjd/AMBER-Membrane_protein_tutorial#1]
Hi,

After checking the manual, the mailing list, and the [Lipid14 tutorial](https://ambermd.org/tutorials/advanced/tutorial16/index.html), I believed the recommendation was to use anisotropic pressure scaling with the Monte Carlo barostat for membrane protein simulations (i.e., `barostat=2, ntp=2`).

Here, it appears you're using semi-isotropic pressure scaling with constant surface tension of 0 dyne/cm. Right?

```
ntp=3
csurften=3
gamma_ten=0.0
ninterface=2
```

I've been running using the former setup (`ntp=2`) and have observed some small-to-moderate buckling of the bilayer in my simulations with membrane proteins after several hundred nanoseconds. I started to look around and landed here. I think that switching to semi-isotropic pressure coupling would prevent the buckling, by linking the pressure in the xy plane, as described. Do you feel that running with semi-isotropic pressure scaling and 0 surface tension is a more reliable setting for membrane protein simulations? In other words, would you say semi-isotropic pressure scaling is the current "best practice" in your experience for using Lipid17?

I'm looking forward to the Lipid17 paper 😅

**Comment by callumjd** [comment]
Hi David,

As you've probably noticed, membrane and membrane protein simulations with amber are still somewhat under-resourced research-wise and tutorial-wise. I've moved into industry but still need to run these simulations, it means I have less time though to look into "best-practices" and updates to the force field. So I wasn't keen to recommend something as a best-practice without real test runs to back it up. Ross Walker has also gone to industry, Ian Gould remains in academia but it just depends who he has in his lab to work on these things.

Anyway, yes I am using semi-isotropic pressure scaling and would stick with these settings:

barostat=1,

ntp=3

csurften=3

gamma_ten=0.0

ninterface=2

I have done some test runs with the Monte Carlo barostat=2, depending on the lipid species this can either be tolerated (POPC seems OK) but with anionic lipids it causes shrinking of the bilayer so I would be careful and do some validation runs. Lipid17 will likely just morph to Lipid20, I have a paper drafted which hopefully we will push out and document these settings.

Best,
Callum



________________________________

**Comment by slochower** [comment]
Ah, yeah—I completely understand your point about resources, which is why this repository is really valuable.

Thanks for confirming your settings and also for the tip on the Monte Carlo barostat with anionic species. That is curious.

**Comment by slochower** [comment]
Just figured I'd circle back and say that after 1 μs, the membrane with semi-isotropic pressure coupling definitely seems better behaved than the anisotropic one.

Anistropic
![anisotropic](https://user-images.githubusercontent.com/5393995/91622697-3f2eb280-e94d-11ea-8e5c-76301592c509.png)

Semi-istropic
![semiisotropic](https://user-images.githubusercontent.com/5393995/91622702-435ad000-e94d-11ea-8d3a-68553ac83ca0.png)

**Comment by callumjd** [comment]
Thanks for closing the loop - yes, the semi-isotropic membrane certainly looks healthier.


________________________________
