### ISSUE TITLE
Lipid20 forcefield availability

### ISSUE THREAD

**Issue by Teohoho** [callumjd/AMBER-Membrane_protein_tutorial#2]
Hello! I am trying to simulate a membrane bilayer which uses Sphingomyelin as a headgroup for one of the lipids involved. I noticed that this tutorial uses the Lipid20 FF, which I've read introduces parameters for SM. However, even after installing AmberTools20, this forcefield remains elusive. I noticed it is used in your tutorial, so I assume it was published somewhere. Can you please let me (and others who Iassume are in my situation) know where you got it from?

Thank you!

**Comment by callumjd** [comment]
Hi there, it has not been released yet. We hit a roadblock with the validation but it should be out soon.
