### ISSUE TITLE
I followed this tutorial, however I found out that the lipid20 was not relesed in Amber20 

### ISSUE THREAD

**Issue by AKBforever** [callumjd/AMBER-Membrane_protein_tutorial#3]
Hi, thank you for your tutorial. When I used the leap script to build the system, one command "source leaprc.lipid20" got an error. I find out that  lipid20 is not released in Amber20 till now. 
So could you tell me where I can download the latest lipid force field?

**Comment by callumjd** [comment]
Apologies - I wanted to "future proof" the tutorial. Lipid21 will be released soon. For the meantime, please use lipid17
