### ISSUE TITLE
Error with ff

### ISSUE THREAD

**Issue by georopon** [callumjd/AMBER-Membrane_protein_tutorial#4]
Dear, 

I'm following your tutorial, but get following error:

Lipid21 was not found in AMBERHOME. Falling back to lipid17!

i'va installed amber tools with Conda.

**Comment by callumjd** [comment]
Hi, lipid21 is only just released and not yet distributed with the Amber package (patch coming soon). You can either:
- download and install lipid21 parameters (from https://github.com/callumjd/lipid21 )
- safely proceed with lipid17
